Use .com instead of .org
Something is wrong with the example.org certificate in the certifi
package (which is up to date).

```
FAILED tests/utils/test_schema.py::test_no_schema - requests.exceptions.SSLError: HTTPSConnectionPool(host='example.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1010)')))
```

This seems to happen both in CircleCI and locally macOS. Updating the
test to use `example.com` allows the test to pass.